name: Run Integration Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Install Temporal CLI
        uses: temporalio/setup-temporal@v0

      - name: Run integration tests
        run: |
          mkdir -p temporal-certs-stg
          echo "$TEMPORAL_CA_PEM" > temporal-certs-stg/cert.pem
          echo "$TEMPORAL_CA_KEY" > temporal-certs-stg/cert_key.pem
          python pantheon_v2/tests/integration_tests.py $TEMPORAL_CERT_FILE_PATH $TEMPORAL_KEY_FILE_PATH $TEMPORAL_NAMESPACE $TEMPORAL_ADDRESS

        env:
          TEMPORAL_CA_PEM: ${{ secrets.TEMPORAL_CA_PEM }}
          TEMPORAL_CA_KEY: ${{ secrets.TEMPORAL_CA_KEY }}
          TEMPORAL_CERT_FILE_PATH: temporal-certs-stg/cert.pem
          TEMPORAL_KEY_FILE_PATH: temporal-certs-stg/cert_key.pem
          TEMPORAL_ADDRESS: zamp-stg-general.dkqth.tmprl.cloud:7233
          TEMPORAL_NAMESPACE: zamp-stg-general.dkqth
