FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y curl && \
    curl -sSf https://temporal.download/cli.sh | sh && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV PATH="/root/.temporalio/bin:${PATH}"

CMD ["temporal", "server", "start-dev", "--ip", "0.0.0.0"]
